export const SELECTORS = {
    COMMENTS: '#comments',
    CONTROLS_CONTAINER: '[data-widget="webListReviews"] > div',
    REVIEWS_LIST: '[data-widget="webListReviews"]',
    REVIEWS: '[data-widget="webListReviews"] > div > div > div[data-review-uuid]',
    REVIEW_CONTENT: ':scope > div:nth-of-type(1) > div:nth-of-type(2)',
    REVIEW_FOOTER: ':scope > div:nth-of-type(1) > div:nth-of-type(3)',
    PRODUCT_VARIATION_WRAP: ':scope > div:nth-of-type(1) a',
    REVIEW_SURVEY_WRAP: ':scope > div:nth-of-type(1) > div > div:nth-of-type(2)',
    REVIEW_TEXT_WRAP: ':scope > div:nth-of-type(2)',
    STICKY_REVIEWS_INFO: '[data-widget="webStickyProducts"] [data-widget="webReviewProductScore"] .tsBodyControl400Small',
    UNNECESSARY_ELEMENTS: '[data-widget="separator"], [data-widget="skuGrid"]',
    PAGINATOR: '[data-widget="paginator"]',
    FILTERS_CONTAINER: '#customFiltersContainer',
    WEB_REVIEW_TABS: '[data-widget="webReviewTabs"]',
};
